# Generated by Django 6.1 on 2026-09-06 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message_sources'),
        ('users', '0002_workspace_workspacemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.workspace'),
        ),
    ]
