# Generated by Django 6.1 on 2026-09-04 13:14

import pgvector.django.vector
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documentchunk"),
    ]

    operations = [
        CreateExtension("vector"),
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="content_type",
            field=models.CharField(max_length=100),
        ),
    ]