# Generated by Django 6.1 on 2026-09-06 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentchunk_embedding_alter_document_content_type'),
        ('users', '0002_workspace_workspacemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.workspace'),
        ),
    ]
