# Generated by Django 6.1 on 2026-09-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_workspace'),
        ('users', '0002_workspace_workspacemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.workspace'),
        ),
    ]
